package model.ApplicationModule.common;

import oracle.jbo.ApplicationModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Feb 27 06:16:55 IST 2022
// ---------------------------------------------------------------------
public interface AppModule extends ApplicationModule {
    void AddMore(int more);

    void GetPrdtDetails(String val);
}
