package model.Entity;

import java.util.Random;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.SequenceImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Feb 21 04:54:07 IST 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class ProductCatogiryEOImpl extends EntityImpl {
    private static EntityDefImpl mDefinitionObject;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. Do not modify.
     */
    public enum AttributesEnum {
        CatogiryId {
            public Object get(ProductCatogiryEOImpl obj) {
                return obj.getCatogiryId();
            }

            public void put(ProductCatogiryEOImpl obj, Object value) {
                obj.setCatogiryId((Number)value);
            }
        }
        ,
        CatogiryName {
            public Object get(ProductCatogiryEOImpl obj) {
                return obj.getCatogiryName();
            }

            public void put(ProductCatogiryEOImpl obj, Object value) {
                obj.setCatogiryName((String)value);
            }
        }
        ,
        ProductsEO {
            public Object get(ProductCatogiryEOImpl obj) {
                return obj.getProductsEO();
            }

            public void put(ProductCatogiryEOImpl obj, Object value) {
                obj.setAttributeInternal(index(), value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static int firstIndex = 0;

        public abstract Object get(ProductCatogiryEOImpl object);

        public abstract void put(ProductCatogiryEOImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }
    public static final int CATOGIRYID = AttributesEnum.CatogiryId.index();
    public static final int CATOGIRYNAME = AttributesEnum.CatogiryName.index();
    public static final int PRODUCTSEO = AttributesEnum.ProductsEO.index();

    /**
     * This is the default constructor (do not remove).
     */
    public ProductCatogiryEOImpl() {
    }

    /**
     * Gets the attribute value for CatogiryId, using the alias name CatogiryId.
     * @return the CatogiryId
     */
    public Number getCatogiryId() {
        return (Number)getAttributeInternal(CATOGIRYID);
    }

    /**
     * Sets <code>value</code> as the attribute value for CatogiryId.
     * @param value value to set the CatogiryId
     */
    public void setCatogiryId(Number value) {
        setAttributeInternal(CATOGIRYID, value);
    }

    /**
     * Gets the attribute value for CatogiryName, using the alias name CatogiryName.
     * @return the CatogiryName
     */
    public String getCatogiryName() {
        return (String)getAttributeInternal(CATOGIRYNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for CatogiryName.
     * @param value value to set the CatogiryName
     */
    public void setCatogiryName(String value) {
        setAttributeInternal(CATOGIRYNAME, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @return the associated entity oracle.jbo.RowIterator.
     */
    public RowIterator getProductsEO() {
        return (RowIterator)getAttributeInternal(PRODUCTSEO);
    }

    /**
     * @param catogiryId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(Number catogiryId) {
        return new Key(new Object[]{catogiryId});
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = EntityDefImpl.findDefObject("model.Entity.ProductCatogiryEO");
        }
        return mDefinitionObject;
    }

    /**
     * Add attribute defaulting logic in this method.
     * @param attributeList list of attribute names/values to initialize the row
     */
    protected void create(AttributeList attributeList) {
        super.create(attributeList);
        Random random = new Random();
        int x = random.nextInt(1000);
        Number num = new Number(x);
        this.setCatogiryId(num);
        
    }

    /**
     * Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**
     * Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**
     * Custom DML update/insert/delete logic here.
     * @param operation the operation type
     * @param e the transaction event
     */
    protected void doDML(int operation, TransactionEvent e) {
        if (operation ==DML_INSERT){
            SequenceImpl se = new SequenceImpl("PD_CAT_SEQ",getDBTransaction());
            this.setCatogiryId(se.getSequenceNumber());
        }
        super.doDML(operation, e);
    
}
}
