package model.ApplicationModule;

import model.ApplicationModule.common.AppModule;

import model.views.CheckOutPVOImpl;
import model.views.ProductsVOImpl;
import model.views.ProductsVORowImpl;

import oracle.adf.model.BindingContext;

import oracle.binding.BindingContainer;
import oracle.binding.OperationBinding;

import oracle.jbo.Row;
import oracle.jbo.RowSet;
import oracle.jbo.RowSetIterator;
import oracle.jbo.ViewCriteria;
import oracle.jbo.domain.Number;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewLinkImpl;
import oracle.jbo.server.ViewObjectImpl;

// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Feb 27 06:08:04 IST 2022
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleImpl extends ApplicationModuleImpl implements AppModule {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleImpl() {
    }

    /**
     * Container's getter for BranchesVO1.
     * @return BranchesVO1
     */
    public ViewObjectImpl getBranchesVO1() {
        return (ViewObjectImpl)findViewObject("BranchesVO1");
    }

    /**
     * Container's getter for CustPrdtVO1.
     * @return CustPrdtVO1
     */
    public ViewObjectImpl getCustPrdtVO1() {
        return (ViewObjectImpl)findViewObject("CustPrdtVO1");
    }

    /**
     * Container's getter for CustomersVO1.
     * @return CustomersVO1
     */
    public ViewObjectImpl getCustomersVO1() {
        return (ViewObjectImpl)findViewObject("CustomersVO1");
    }

    /**
     * Container's getter for DepartmentsVO1.
     * @return DepartmentsVO1
     */
    public ViewObjectImpl getDepartmentsVO1() {
        return (ViewObjectImpl)findViewObject("DepartmentsVO1");
    }

    /**
     * Container's getter for EmployeesVO1.
     * @return EmployeesVO1
     */
    public ViewObjectImpl getEmployeesVO1() {
        return (ViewObjectImpl)findViewObject("EmployeesVO1");
    }

    /**
     * Container's getter for OrdersVO1.
     * @return OrdersVO1
     */
    public ViewObjectImpl getOrdersVO1() {
        return (ViewObjectImpl)findViewObject("OrdersVO1");
    }

    /**
     * Container's getter for PrdtRcptVO1.
     * @return PrdtRcptVO1
     */
    public ViewObjectImpl getPrdtRcptVO1() {
        return (ViewObjectImpl)findViewObject("PrdtRcptVO1");
    }

    /**
     * Container's getter for ProductCatogiryVO1.
     * @return ProductCatogiryVO1
     */
    public ViewObjectImpl getProductCatogiryVO1() {
        return (ViewObjectImpl)findViewObject("ProductCatogiryVO1");
    }

    /**
     * Container's getter for ProductsVO1.
     * @return ProductsVO1
     */
    public ViewObjectImpl getProductsVO1() {
        return (ViewObjectImpl)findViewObject("ProductsVO1");
    }

    /**
     * Container's getter for RecptsVO1.
     * @return RecptsVO1
     */
    public ViewObjectImpl getRecptsVO1() {
        return (ViewObjectImpl)findViewObject("RecptsVO1");
    }

    /**
     * Container's getter for SupplierVO1.
     * @return SupplierVO1
     */
    public ViewObjectImpl getSupplierVO1() {
        return (ViewObjectImpl)findViewObject("SupplierVO1");
    }

    /**
     * Container's getter for CustPrdtVO2.
     * @return CustPrdtVO2
     */
    public ViewObjectImpl getCustPrdtVO2() {
        return (ViewObjectImpl)findViewObject("CustPrdtVO2");
    }

    /**
     * Container's getter for EmployeesVO2.
     * @return EmployeesVO2
     */
    public ViewObjectImpl getEmployeesVO2() {
        return (ViewObjectImpl)findViewObject("EmployeesVO2");
    }

    /**
     * Container's getter for EmployeesVO3.
     * @return EmployeesVO3
     */
    public ViewObjectImpl getEmployeesVO3() {
        return (ViewObjectImpl)findViewObject("EmployeesVO3");
    }

    /**
     * Container's getter for OrdersVO2.
     * @return OrdersVO2
     */
    public ViewObjectImpl getOrdersVO2() {
        return (ViewObjectImpl)findViewObject("OrdersVO2");
    }

    /**
     * Container's getter for PrdtRcptVO2.
     * @return PrdtRcptVO2
     */
    public ViewObjectImpl getPrdtRcptVO2() {
        return (ViewObjectImpl)findViewObject("PrdtRcptVO2");
    }

    /**
     * Container's getter for CustPrdtVO3.
     * @return CustPrdtVO3
     */
    public ViewObjectImpl getCustPrdtVO3() {
        return (ViewObjectImpl)findViewObject("CustPrdtVO3");
    }

    /**
     * Container's getter for ProductsVO2.
     * @return ProductsVO2
     */
    public ViewObjectImpl getProductsVO2() {
        return (ViewObjectImpl)findViewObject("ProductsVO2");
    }

    /**
     * Container's getter for PrdtRcptVO3.
     * @return PrdtRcptVO3
     */
    public ViewObjectImpl getPrdtRcptVO3() {
        return (ViewObjectImpl)findViewObject("PrdtRcptVO3");
    }

    /**
     * Container's getter for RecptsVO2.
     * @return RecptsVO2
     */
    public ViewObjectImpl getRecptsVO2() {
        return (ViewObjectImpl)findViewObject("RecptsVO2");
    }

    /**
     * Container's getter for RecptsVO3.
     * @return RecptsVO3
     */
    public ViewObjectImpl getRecptsVO3() {
        return (ViewObjectImpl)findViewObject("RecptsVO3");
    }

    /**
     * Container's getter for ProductsVO3.
     * @return ProductsVO3
     */
    public ViewObjectImpl getProductsVO3() {
        return (ViewObjectImpl)findViewObject("ProductsVO3");
    }

    /**
     * Container's getter for SupplierVO2.
     * @return SupplierVO2
     */
    public ViewObjectImpl getSupplierVO2() {
        return (ViewObjectImpl)findViewObject("SupplierVO2");
    }

    /**
     * Container's getter for GenderSVO1.
     * @return GenderSVO1
     */
    public ViewObjectImpl getGenderSVO1() {
        return (ViewObjectImpl)findViewObject("GenderSVO1");
    }

    /**
     * Container's getter for UnitsVO1.
     * @return UnitsVO1
     */
    public ViewObjectImpl getUnitsVO1() {
        return (ViewObjectImpl)findViewObject("UnitsVO1");
    }

    /**
     * Container's getter for CustPrdtCustomersFk1Link1.
     * @return CustPrdtCustomersFk1Link1
     */
    public ViewLinkImpl getCustPrdtCustomersFk1Link1() {
        return (ViewLinkImpl)findViewLink("CustPrdtCustomersFk1Link1");
    }

    /**
     * Container's getter for EmpBrnchFk1Link1.
     * @return EmpBrnchFk1Link1
     */
    public ViewLinkImpl getEmpBrnchFk1Link1() {
        return (ViewLinkImpl)findViewLink("EmpBrnchFk1Link1");
    }

    /**
     * Container's getter for EmpDepFk1Link1.
     * @return EmpDepFk1Link1
     */
    public ViewLinkImpl getEmpDepFk1Link1() {
        return (ViewLinkImpl)findViewLink("EmpDepFk1Link1");
    }

    /**
     * Container's getter for OrdersCustFk1Link1.
     * @return OrdersCustFk1Link1
     */
    public ViewLinkImpl getOrdersCustFk1Link1() {
        return (ViewLinkImpl)findViewLink("OrdersCustFk1Link1");
    }

    /**
     * Container's getter for PrdtRcptProductsFk1Link1.
     * @return PrdtRcptProductsFk1Link1
     */
    public ViewLinkImpl getPrdtRcptProductsFk1Link1() {
        return (ViewLinkImpl)findViewLink("PrdtRcptProductsFk1Link1");
    }

    /**
     * Container's getter for CustPrdtProductsFk1Link1.
     * @return CustPrdtProductsFk1Link1
     */
    public ViewLinkImpl getCustPrdtProductsFk1Link1() {
        return (ViewLinkImpl)findViewLink("CustPrdtProductsFk1Link1");
    }

    /**
     * Container's getter for ProdCatFk1Link1.
     * @return ProdCatFk1Link1
     */
    public ViewLinkImpl getProdCatFk1Link1() {
        return (ViewLinkImpl)findViewLink("ProdCatFk1Link1");
    }

    /**
     * Container's getter for PrdtRcptRecptsFk1Link1.
     * @return PrdtRcptRecptsFk1Link1
     */
    public ViewLinkImpl getPrdtRcptRecptsFk1Link1() {
        return (ViewLinkImpl)findViewLink("PrdtRcptRecptsFk1Link1");
    }

    /**
     * Container's getter for RecptsCustomersFk1Link1.
     * @return RecptsCustomersFk1Link1
     */
    public ViewLinkImpl getRecptsCustomersFk1Link1() {
        return (ViewLinkImpl)findViewLink("RecptsCustomersFk1Link1");
    }

    /**
     * Container's getter for RecptsEmployeesFk1Link1.
     * @return RecptsEmployeesFk1Link1
     */
    public ViewLinkImpl getRecptsEmployeesFk1Link1() {
        return (ViewLinkImpl)findViewLink("RecptsEmployeesFk1Link1");
    }

    /**
     * Container's getter for ProdSupFk1Link1.
     * @return ProdSupFk1Link1
     */
    public ViewLinkImpl getProdSupFk1Link1() {
        return (ViewLinkImpl)findViewLink("ProdSupFk1Link1");
    }

    /**
     * Container's getter for SupplierBranchFk1Link1.
     * @return SupplierBranchFk1Link1
     */
    public ViewLinkImpl getSupplierBranchFk1Link1() {
        return (ViewLinkImpl)findViewLink("SupplierBranchFk1Link1");
    }
    
//    public void AddMore(int more) {
//    }

    public void AddMore(int more) {
    }

    /**
     * Container's getter for SearchVO1.
     * @return SearchVO1
     */
    public ViewObjectImpl getSearchVO1() {
        return (ViewObjectImpl)findViewObject("SearchVO1");
    }

    /**
     * Container's getter for CheckOutPVO1.
     * @return CheckOutPVO1
     */
    public CheckOutPVOImpl getCheckOutPVO1() {
        return (CheckOutPVOImpl)findViewObject("CheckOutPVO1");
    }

    /**
     * Container's getter for CheckoutVO1.
     * @return CheckoutVO1
     */
    public ViewObjectImpl getCheckoutVO1() {
        return (ViewObjectImpl)findViewObject("CheckoutVO1");
    }
    
    public void GetPrdtDetails(String val){
        ViewObjectImpl vo = this.getProductsVO1();
               ViewCriteria vc = vo.getViewCriteria("srchPrdt");
               vo.setNamedWhereClauseParam("PrdtId", val);
               vo.applyViewCriteria(vc);
               vo.executeQuery();
        RowSetIterator rs = vo.createRowSetIterator(null);
                while (rs.hasNext()) {
                    Row r = rs.next();
                    ViewObjectImpl vo1 = this.getCheckOutPVO1();
                    Row r1 = vo1.createRow();
                    r1.setAttribute("ItemDesc", r.getAttribute("PrdtName"));
                    r1.setAttribute("Value", r.getAttribute("SellngPs"));
                    vo1.insertRow(r1);
                    
                }
    }
}
